version: 2.1
workflows:
  cci-agent-setup:
    jobs:
      - cci-agent-setup
jobs:
  cci-agent-setup:
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Install Playwright browsers
          command: |
            npx playwright install --with-deps
      - run:
          name: Build project
          command: |
            npm run build:prod
      # insert more environment setup here
